"""0001_create_patient_journey_schedule_window

Revision ID: 577ec630a715
Revises: a3cfbbeab93d
Create Date: 2025-02-09 16:36:32.541581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '577ec630a715'
down_revision: Union[str, None] = 'a3cfbbeab93d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_journey_schedule_window',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('patient_journey_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('activity_content_slug', sa.String(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('schedule_slug', sa.String(), nullable=True),
    sa.Column('schedule_start_offset_days', sa.Integer(), nullable=True),
    sa.Column('schedule_end_offset_days', sa.Integer(), nullable=True),
    sa.Column('schedule_milestone_slug', sa.String(), nullable=True),
    sa.Column('inserted_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('patient_id', 'patient_journey_id'),
    comment='PostgreSQL - MSK database'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_journey_schedule_window')
    # ### end Alembic commands ###
