name: msk-etl

on:
    pull_request:
      paths:
        - msk/**
      branches: [master]

jobs:
  unittests:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Run unittests
        working-directory: msk/
        run: ./ci-tests.sh

      - name: Coverage Report
        uses: orgoro/coverage@v3.1
        with:
          coverageFile: msk/etls/coverage.xml
          thresholdAll: 0.2
          token: ${{ github.token }}